#
# Graphics support
#

#
# I2C encoder or helper chips
#
CONFIG_DRM_I2C_CH7006=n
CONFIG_DRM_I2C_SIL164=n
CONFIG_DRM_I2C_NXP_TDA998X=n


#
# ARM devices
#
CONFIG_DRM_HDLCD=n
CONFIG_DRM_MALI_DISPLAY=n
CONFIG_DRM_KOMEDA=n


CONFIG_DRM_NOUVEAU=n
CONFIG_DRM_ROCKCHIP=n
CONFIG_ROCKCHIP_VOP=n
CONFIG_ROCKCHIP_DW_HDMI=n
CONFIG_ROCKCHIP_ANALOGIX_DP=n
CONFIG_ROCKCHIP_CDN_DP=n
CONFIG_ROCKCHIP_DW_MIPI_DSI=n
CONFIG_ROCKCHIP_INNO_HDMI=n
CONFIG_ROCKCHIP_LVDS=n
CONFIG_DRM_RCAR_MIPI_DSI=n
CONFIG_DRM_RCAR_DW_HDMI=n
CONFIG_DRM_PANEL_BOE_TV101WUM_NL6
CONFIG_DRM_PANEL_MANTIX_MLAF057WE51=n
CONFIG_DRM_PANEL_RAYDIUM_RM67191=n
CONFIG_DRM_PANEL_SITRONIX_ST7703=n
CONFIG_DRM_PANEL_TRULY_NT35597_WQXGA=n
# CONFIG_DRM_LONTIUM_LT8912B is not set
# CONFIG_DRM_LONTIUM_LT9611 is not set
# CONFIG_DRM_LONTIUM_LT9611UXC is not set
# CONFIG_DRM_PARADE_PS8640 is not set
# CONFIG_DRM_SII902X is not set
# CONFIG_DRM_SIMPLE_BRIDGE is not set
# CONFIG_DRM_THINE_THC63LVD1024 is not set
# CONFIG_DRM_TI_SN65DSI86 is not set
# CONFIG_DRM_I2C_ADV7511 is not set
# CONFIG_DRM_CDNS_MHDP8546 is not set
# CONFIG_DRM_HISI_HIBMC is not set
# CONFIG_DRM_HISI_KIRIN is not set
# CONFIG_DRM_PL111 is not set
# CONFIG_DRM_LIMA is not set
# CONFIG_DRM_TIDSS is not set

CONFIG_DRM_DISPLAY_CONNECTOR=m
